### ISSUE TITLE
Preventive Maintenance Tracking 

### ISSUE THREAD

**Issue by mattandwhatnot** [commutron/neptune-dev#48]
Module to record recurring preventative maintenance tasks

**Comment by mattandwhatnot** [comment]
- [ ] Equipment Setup/Edit
- [ ] Equipment On/Off line
- [ ] Equipment Delete
- [ ] Service Pattern Setup
- [ ] Tasks Setup
- [ ] Select Service From Production
- [ ] Construct Maintenance-Production Interface 
- [ ] Retrieve Next Required Service
- [ ] Retrieve In Service Window Now
- [ ] Record Maintenance Tasks
- [ ] Record Maintenance Time
- [ ] Notify on Missed/Incomplete Service
- [ ] Generate Future PM Calendar
- [ ] View Equipment's Maintenance History
- [ ] Interface & Usability
- [ ] Integrate Maintenance Time into User Time Records
- [ ] Integrate Maintenance Time into People Time Monitoring
- [ ] Overview Integration

**Comment by mattandwhatnot** [comment]
Phase on complete and released
